### ISSUE TITLE
Link to blog post on README.md is broken

### ISSUE THREAD

**Issue by GuiSim** [chriso/redback#34]
The link to http://chris6f.com/rate-limiting-with-redis does not work.

Is there a mirror somewhere or another relevant page that could explain the algorithm?

Meanwhile, you can use https://web.archive.org/web/20131220125148/https://chris6f.com/rate-limiting-with-redis

**Comment by chriso** [comment]
Thanks. I've made a copy available at https://gist.github.com/chriso/54dd46b03155fcf555adccea822193da.
