### ISSUE TITLE
CappedList.unshift makes no sense

### ISSUE THREAD

**Issue by srgl** [chriso/redback#36]
What is the purpose of the `CappedList.unshift`? It does nothing as soon as a list get max length.

**Comment by srgl** [comment]
I guess it is due to the wrong trimming indices here https://github.com/chriso/redback/blob/master/lib/advanced_structures/CappedList.js#L100
should be `multi.ltrim(this.key, 0, this.len)`
Am I correct?

**Comment by chriso** [comment]
You're right, yeah, that looks like a bug.
